doctrine_migrations:
    migrations_paths:
        App\Infrastructure\Shared\Migrations: '%kernel.project_dir%/src/Infrastructure/Shared/Migrations'

    connection: default

    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            version_column_length: 1024
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'
